### ISSUE TITLE
KeyError: 'PATH'

### ISSUE THREAD

**Issue by Chris-SG** [rundeck-plugins/py-winrm-plugin#23]
Whenever I try to do a file-transfer using this, I seem to run into the same error:

```14:48:43	Task	 1. Test	Traceback (most recent call last):
14:48:43			  File "C:\Users\user\Desktop\rundeck\libext\cache\py-winrm-plugin-2.0.0\winrm-filecopier.py", line 1, in <module>
14:48:43			    import winrm
14:48:43			  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\winrm\__init__.py", line 6, in <module>
14:48:43			    from winrm.protocol import Protocol
14:48:43			  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\winrm\protocol.py", line 11, in <module>
14:48:43			    from winrm.transport import Transport
14:48:43			  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\winrm\transport.py", line 15, in <module>
14:48:43			    import requests
14:48:43			  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\__init__.py", line 95, in <module>
14:48:43			    from urllib3.contrib import pyopenssl
14:48:43			  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\contrib\pyopenssl.py", line 46, in <module>
14:48:43			    import OpenSSL.SSL
14:48:43			  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
14:48:43			    from OpenSSL import crypto, SSL
14:48:43			  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\OpenSSL\crypto.py", line 12, in <module>
14:48:43			    from cryptography import x509
14:48:43			  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cryptography\x509\__init__.py", line 8, in <module>
14:48:43			    from cryptography.x509.base import (
14:48:43			  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cryptography\x509\base.py", line 16, in <module>
14:48:43			    from cryptography.x509.extensions import Extension, ExtensionType
14:48:43			  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cryptography\x509\extensions.py", line 13, in <module>
14:48:43			    from asn1crypto.keys import PublicKeyInfo
14:48:43			  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\asn1crypto\keys.py", line 22, in <module>
14:48:43			    from ._elliptic_curve import (
14:48:43			  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\asn1crypto\_elliptic_curve.py", line 51, in <module>
14:48:43			    from ._int import inverse_mod
14:48:43			  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\asn1crypto\_int.py", line 56, in <module>
14:48:43			    from ._perf._big_num_ctypes import libcrypto
14:48:43			  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\asn1crypto\_perf\_big_num_ctypes.py", line 35, in <module>
14:48:43			    libcrypto_path = find_library(b'crypto' if sys.version_info < (3,) else 'crypto')
14:48:43			  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\ctypes\util.py", line 59, in find_library
14:48:43			    for directory in os.environ['PATH'].split(os.pathsep):
14:48:43			  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\os.py", line 669, in __getitem__
14:48:43			    raise KeyError(key) from None
14:48:43			KeyError: 'PATH'```

I have tried various versions of python (2.7, 3.5, 3.6, 3.7) alongside various releases of pywinrm.

Starting to run out of ideas of the cause, although I can confirm PATH is an envvar for both system and user.

**Comment by ltamaster** [comment]
Hi @Chris-SG ,

I think I found the problem, let me know if that works for you

Luis

**Comment by Chris-SG** [comment]
Looks like it worked, cheers!
