### ISSUE TITLE
RequestsDependencyWarning on Rundeck job execution

### ISSUE THREAD

**Issue by matthgyver** [rundeck-plugins/py-winrm-plugin#6]
Hi,

I'm using the last plugin version delivred with Rundeck v. 2.11.3-1 and have this error when I'm trying a simple command execution or a simple job with a command like ``get-childitem c:`` : 
```/usr/lib/python2.7/site-packages/requests-2.18.4-py2.7.egg/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.10.2) or chardet (2.2.1) doesn't match a supported version!
RequestsDependencyWarning)
Traceback (most recent call last):
  File "/var/lib/rundeck/libext/cache/py-winrm-plugin-1.0.4/winrm-exec.py", line 1, in <module>
    import winrm
  File "build/bdist.linux-x86_64/egg/winrm/__init__.py", line 6, in <module>
  File "build/bdist.linux-x86_64/egg/winrm/protocol.py", line 11, in <module>
  File "build/bdist.linux-x86_64/egg/winrm/transport.py", line 15, in <module>
  File "/usr/lib/python2.7/site-packages/requests-2.18.4-py2.7.egg/requests/__init__.py", line 90, in <module>
    from urllib3.exceptions import DependencyWarning
ImportError: cannot import name DependencyWarning
[WinRMPython]: result code: 1, success: false
Failed: NonZeroResultCode: [WinRMPython] Result code: 1
```
I've the latest **urllib3 (version 1.22)** and **cardet (version 3.0.4)**.
I've trying to downgrade this lib but the problem still here.

If I'm using the winrm-check script I've no problem.

Could you help me to solve this problem please ?

Thank you

**Comment by matthgyver** [comment]
Hi,

That was a conflict with Python library installed with yum and with pip.
Uninstalling redhat package solve the problem.
