### ISSUE TITLE
Executing jobs on Windows 2012r2 Servers keep failing

### ISSUE THREAD

**Issue by brrratz** [rundeck-plugins/py-winrm-plugin#80]
Hi,

since a few days we receiving error messages from Windows Server 2012r2 Hosts (atm only 2012r2 hosts seems to be affected).

`Traceback (most recent call last):
  File "f:\rundeck\libext\cache\py-winrm-plugin-2.0.12\winrm-filecopier.py", line 380, in <module>
    quiet=quiet)
  File "f:\rundeck\libext\cache\py-winrm-plugin-2.0.12\winrm-filecopier.py", line 210, in winrm_upload
    raise WinRmError(script, code, stdout, stderr)
__main__.WinRmError: Remote execution of "add-content -value $([System.Convert]::FromBase64String("aG9zdG5hbWUNCg==")) -encoding byte -path C:\WINDOWS\TEMP\9-527503-XXXX-dispatch-script.tmp.ps1" failed with exit code 1. STDOUT: . STDERR: .
Failed dispatching to node XXXX: [WinRMcpPython]: external script failed with exit code: 1
Execution failed: 527503 in project AMI: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: XXXX NonZeroResultCode: [WinRMcpPython]: external script failed with exit code: 1]}, Node failures: {XXXX=[NonZeroResultCode: [WinRMcpPython]: external script failed with exit code: 1]}, status: failed]`

Tbh, i really dont know where i have to search for the issue - of course it could be a problem of the destination.
I would be glad if someone has an advice!

greets

**Comment by fdevans** [comment]
Sorry we missed this. If it's still a problem please open a new Issue with current Rundeck version details, and a deeper description of how this can be repeated.
